//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contacts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub is_customer: bool,
    pub is_supplier: bool,
    pub street1: String,
    pub street2: String,
    pub postal_code: String,
    pub city: String,
    pub country: String,
    pub customer_account_id: Option<i32>,
    pub supplier_account_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ledger_accounts::Entity",
        from = "Column::CustomerAccountId",
        to = "super::ledger_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerAccounts2,
    #[sea_orm(
        belongs_to = "super::ledger_accounts::Entity",
        from = "Column::SupplierAccountId",
        to = "super::ledger_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerAccounts1,
    #[sea_orm(has_many = "super::purchase_invoices::Entity")]
    PurchaseInvoices,
    #[sea_orm(has_many = "super::purchase_orders::Entity")]
    PurchaseOrders,
    #[sea_orm(has_many = "super::sale_invoices::Entity")]
    SaleInvoices,
    #[sea_orm(has_many = "super::sale_orders::Entity")]
    SaleOrders,
    #[sea_orm(has_many = "super::stocks::Entity")]
    Stocks,
}

impl Related<super::purchase_invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseInvoices.def()
    }
}

impl Related<super::purchase_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseOrders.def()
    }
}

impl Related<super::sale_invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleInvoices.def()
    }
}

impl Related<super::sale_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleOrders.def()
    }
}

impl Related<super::stocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stocks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
