//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ledger_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub account_type: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::taxes::Entity")]
    Taxes,
}

impl Related<super::taxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Taxes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
