//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ledger_transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: Date,
    pub amount: i32,
    pub debit_account_id: i32,
    pub credit_account_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ledger_accounts::Entity",
        from = "Column::CreditAccountId",
        to = "super::ledger_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerAccounts2,
    #[sea_orm(
        belongs_to = "super::ledger_accounts::Entity",
        from = "Column::DebitAccountId",
        to = "super::ledger_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerAccounts1,
}

impl ActiveModelBehavior for ActiveModel {}
