//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod contacts;
pub mod ledger_accounts;
pub mod ledger_transactions;
pub mod products;
pub mod purchase_invoice_lines;
pub mod purchase_invoices;
pub mod purchase_order_lines;
pub mod purchase_orders;
pub mod sale_invoice_lines;
pub mod sale_invoices;
pub mod sale_order_lines;
pub mod sale_orders;
pub mod sea_orm_active_enums;
pub mod stock_moves;
pub mod stocks;
pub mod taxes;
pub mod users;
pub mod variants;
