//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::contacts::Entity as Contacts;
pub use super::ledger_accounts::Entity as LedgerAccounts;
pub use super::ledger_transactions::Entity as LedgerTransactions;
pub use super::products::Entity as Products;
pub use super::purchase_invoice_lines::Entity as PurchaseInvoiceLines;
pub use super::purchase_invoices::Entity as PurchaseInvoices;
pub use super::purchase_order_lines::Entity as PurchaseOrderLines;
pub use super::purchase_orders::Entity as PurchaseOrders;
pub use super::sale_invoice_lines::Entity as SaleInvoiceLines;
pub use super::sale_invoices::Entity as SaleInvoices;
pub use super::sale_order_lines::Entity as SaleOrderLines;
pub use super::sale_orders::Entity as SaleOrders;
pub use super::stock_moves::Entity as StockMoves;
pub use super::stocks::Entity as Stocks;
pub use super::taxes::Entity as Taxes;
pub use super::users::Entity as Users;
pub use super::variants::Entity as Variants;
