//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::PurchaseInvoiceStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "purchase_invoices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub reference: String,
    pub date: Date,
    pub status: PurchaseInvoiceStatus,
    pub order_id: i32,
    pub supplier_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contacts::Entity",
        from = "Column::SupplierId",
        to = "super::contacts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Contacts,
    #[sea_orm(has_many = "super::purchase_invoice_lines::Entity")]
    PurchaseInvoiceLines,
    #[sea_orm(
        belongs_to = "super::purchase_orders::Entity",
        from = "Column::OrderId",
        to = "super::purchase_orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PurchaseOrders,
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contacts.def()
    }
}

impl Related<super::purchase_invoice_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseInvoiceLines.def()
    }
}

impl Related<super::purchase_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
