//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "purchase_invoice_lines")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub description: String,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    pub price: i32,
    pub tax: i32,
    pub invoice_id: i32,
    pub variant_id: Option<i32>,
    pub transaction_id: Option<i32>,
    pub tax_id: Option<i32>,
    pub tax_transaction_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ledger_transactions::Entity",
        from = "Column::TaxTransactionId",
        to = "super::ledger_transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerTransactions2,
    #[sea_orm(
        belongs_to = "super::ledger_transactions::Entity",
        from = "Column::TransactionId",
        to = "super::ledger_transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerTransactions1,
    #[sea_orm(
        belongs_to = "super::purchase_invoices::Entity",
        from = "Column::InvoiceId",
        to = "super::purchase_invoices::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    PurchaseInvoices,
    #[sea_orm(
        belongs_to = "super::taxes::Entity",
        from = "Column::TaxId",
        to = "super::taxes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Taxes,
    #[sea_orm(
        belongs_to = "super::variants::Entity",
        from = "Column::VariantId",
        to = "super::variants::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Variants,
}

impl Related<super::purchase_invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseInvoices.def()
    }
}

impl Related<super::taxes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Taxes.def()
    }
}

impl Related<super::variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Variants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
