//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SaleOrderStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sale_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub reference: String,
    pub date: Date,
    pub status: SaleOrderStatus,
    pub customer_id: i32,
    pub source_stock_id: i32,
    pub target_stock_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contacts::Entity",
        from = "Column::CustomerId",
        to = "super::contacts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Contacts,
    #[sea_orm(has_many = "super::sale_invoices::Entity")]
    SaleInvoices,
    #[sea_orm(has_many = "super::sale_order_lines::Entity")]
    SaleOrderLines,
    #[sea_orm(
        belongs_to = "super::stocks::Entity",
        from = "Column::SourceStockId",
        to = "super::stocks::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Stocks2,
    #[sea_orm(
        belongs_to = "super::stocks::Entity",
        from = "Column::TargetStockId",
        to = "super::stocks::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Stocks1,
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contacts.def()
    }
}

impl Related<super::sale_invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleInvoices.def()
    }
}

impl Related<super::sale_order_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleOrderLines.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
