//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::SaleInvoiceStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sale_invoices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub reference: String,
    pub date: Date,
    pub status: SaleInvoiceStatus,
    pub order_id: i32,
    pub customer_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contacts::Entity",
        from = "Column::CustomerId",
        to = "super::contacts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Contacts,
    #[sea_orm(has_many = "super::sale_invoice_lines::Entity")]
    SaleInvoiceLines,
    #[sea_orm(
        belongs_to = "super::sale_orders::Entity",
        from = "Column::OrderId",
        to = "super::sale_orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SaleOrders,
}

impl Related<super::contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contacts.def()
    }
}

impl Related<super::sale_invoice_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleInvoiceLines.def()
    }
}

impl Related<super::sale_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
