//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "sale_order_lines")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub description: String,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    pub price: i32,
    pub tax: i32,
    pub order_id: i32,
    pub variant_id: Option<i32>,
    pub move_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sale_orders::Entity",
        from = "Column::OrderId",
        to = "super::sale_orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    SaleOrders,
    #[sea_orm(
        belongs_to = "super::stock_moves::Entity",
        from = "Column::MoveId",
        to = "super::stock_moves::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    StockMoves,
    #[sea_orm(
        belongs_to = "super::variants::Entity",
        from = "Column::VariantId",
        to = "super::variants::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Variants,
}

impl Related<super::sale_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleOrders.def()
    }
}

impl Related<super::stock_moves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockMoves.def()
    }
}

impl Related<super::variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Variants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
