//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "purchase_invoice_status"
)]
pub enum PurchaseInvoiceStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "finished")]
    Finished,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "purchase_order_status"
)]
pub enum PurchaseOrderStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "finished")]
    Finished,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "sale_invoice_status"
)]
pub enum SaleInvoiceStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "proforma")]
    Proforma,
    #[sea_orm(string_value = "invoice")]
    Invoice,
    #[sea_orm(string_value = "finished")]
    Finished,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "sale_order_status")]
pub enum SaleOrderStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "quotation")]
    Quotation,
    #[sea_orm(string_value = "order")]
    Order,
    #[sea_orm(string_value = "finished")]
    Finished,
}
