//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stock_moves")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    pub variant_id: i32,
    pub source_stock_id: i32,
    pub target_stock_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::purchase_order_lines::Entity")]
    PurchaseOrderLines,
    #[sea_orm(has_many = "super::sale_order_lines::Entity")]
    SaleOrderLines,
    #[sea_orm(
        belongs_to = "super::stocks::Entity",
        from = "Column::SourceStockId",
        to = "super::stocks::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Stocks2,
    #[sea_orm(
        belongs_to = "super::stocks::Entity",
        from = "Column::TargetStockId",
        to = "super::stocks::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Stocks1,
    #[sea_orm(
        belongs_to = "super::variants::Entity",
        from = "Column::VariantId",
        to = "super::variants::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Variants,
}

impl Related<super::purchase_order_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseOrderLines.def()
    }
}

impl Related<super::sale_order_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleOrderLines.def()
    }
}

impl Related<super::variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Variants.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
