//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "taxes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub name_short: String,
    #[sea_orm(column_type = "Double")]
    pub rate: f64,
    pub account_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ledger_accounts::Entity",
        from = "Column::AccountId",
        to = "super::ledger_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LedgerAccounts,
    #[sea_orm(has_many = "super::purchase_invoice_lines::Entity")]
    PurchaseInvoiceLines,
    #[sea_orm(has_many = "super::sale_invoice_lines::Entity")]
    SaleInvoiceLines,
}

impl Related<super::ledger_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerAccounts.def()
    }
}

impl Related<super::purchase_invoice_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseInvoiceLines.def()
    }
}

impl Related<super::sale_invoice_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleInvoiceLines.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
