//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "variants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub sale_price: i32,
    pub purchase_price: i32,
    pub product_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(has_many = "super::purchase_invoice_lines::Entity")]
    PurchaseInvoiceLines,
    #[sea_orm(has_many = "super::purchase_order_lines::Entity")]
    PurchaseOrderLines,
    #[sea_orm(has_many = "super::sale_invoice_lines::Entity")]
    SaleInvoiceLines,
    #[sea_orm(has_many = "super::sale_order_lines::Entity")]
    SaleOrderLines,
    #[sea_orm(has_many = "super::stock_moves::Entity")]
    StockMoves,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::purchase_invoice_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseInvoiceLines.def()
    }
}

impl Related<super::purchase_order_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseOrderLines.def()
    }
}

impl Related<super::sale_invoice_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleInvoiceLines.def()
    }
}

impl Related<super::sale_order_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaleOrderLines.def()
    }
}

impl Related<super::stock_moves::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockMoves.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
